from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5 import QtGui, QtCore
from PyQt5.QtCore import Qt

class General(QWidget):
    def __init__(self, Window):
        super().__init__()
        self.obj = Window
        self.vbox = QVBoxLayout()
        self.addContents()
        self.setLayout(self.vbox)

    def addContents(self):

        
        hbox = QHBoxLayout()
        infoboxwidget = QWidget()
        infobox = QVBoxLayout()
        infobox.setAlignment(Qt.AlignTop)
        infoboxwidget.setMinimumWidth(350)
        infoboxwidget.setLayout(infobox)

        thumbnailvbox = QVBoxLayout()
        thumbnailvbox.setAlignment(Qt.AlignTop)
        previewlayout = QHBoxLayout()
        previewlayout.setAlignment(Qt.AlignLeft)
        previewlabelimg = QLabel()
        previewlabelimg.setPixmap(QPixmap("img/preview.png"))
        previewlabel = QLabel("<b>Preview</b>")
        previewlayout.addWidget(previewlabelimg)
        previewlayout.addWidget(previewlabel)
        self.labelThumbnail = QLabel()
        pixmap = QScreen.grabWindow(QApplication.primaryScreen(), QApplication.desktop().winId())
        pixmap = pixmap.scaled(300, 210, Qt.KeepAspectRatio, transformMode = Qt.SmoothTransformation)
        self.labelThumbnail.setPixmap(pixmap)
        self.labelThumbnail.setStyleSheet("border: 7px solid #858585; border-style: inset;")
        # self.labelThumbnail.setMaximumHeight(155)
        # self.labelThumbnail.setMaximumWidth(255)
        self.labelThumbnail.setAlignment(Qt.AlignTop)

        thumbnailvbox.addLayout(previewlayout)
        thumbnailvbox.addWidget(self.labelThumbnail)
        thumbnailtemp = QVBoxLayout()
        thumbnailtemp.addLayout(thumbnailvbox)
        thumbnailtemp.setAlignment(Qt.AlignRight)


        machinenamelayout = QHBoxLayout()
        machinenamelayout.setAlignment(Qt.AlignLeft)
        machineicon = QLabel()
        machineicon.setPixmap(QPixmap('img/machine.png'))
        machinelabel = QLabel("<b>Machine</b>")
        self.machinevalue = QLabel("Unknown")
        machinenamelayout.addWidget(machineicon)
        machinenamelayout.addWidget(machinelabel)
        machinenamelayout.addWidget(self.machinevalue)
        
        oslayout = QHBoxLayout()
        oslayout.setAlignment(Qt.AlignLeft)
        osicon = QLabel()
        osicon.setPixmap(QPixmap('img/os.png'))
        oslabel = QLabel("<b>Operating System</b>")
        self.osvalue = QLabel("Unknown")
        oslayout.addWidget(osicon)
        oslayout.addWidget(oslabel)
        oslayout.addWidget(self.osvalue)
        
        activeuserlayout = QHBoxLayout()
        activeuserlayout.setAlignment(Qt.AlignLeft)
        activeusericon = QLabel()
        activeusericon.setPixmap(QPixmap('img/user.png'))
        activeuserlabel = QLabel("<b>Username</b>")
        self.activeuservalue = QLabel("Unknown")
        activeuserlayout.addWidget(activeusericon)
        activeuserlayout.addWidget(activeuserlabel)
        activeuserlayout.addWidget(self.activeuservalue)

        uptimelayout = QHBoxLayout()
        uptimelayout.setAlignment(Qt.AlignLeft)
        uptimeicon = QLabel()
        uptimeicon.setPixmap(QPixmap('img/time.png'))
        uptimelabel = QLabel("<b>Machine Uptime</b>")
        self.uptimevalue = QLabel("0.0")
        uptimelayout.addWidget(uptimeicon)
        uptimelayout.addWidget(uptimelabel)
        uptimelayout.addWidget(self.uptimevalue)

        cpulayout = QHBoxLayout()
        cpulayout.setAlignment(Qt.AlignLeft)
        cpuicon = QLabel()
        cpuicon.setPixmap(QPixmap('img/cpu.png'))
        cpulabel = QLabel("<b>CPU Usage</b>")
        self.cpuvalue = QLabel("0.0")
        cpulayout.addWidget(cpuicon)
        cpulayout.addWidget(cpulabel)
        cpulayout.addWidget(self.cpuvalue)

        memorylayout = QHBoxLayout()
        memorylayout.setAlignment(Qt.AlignLeft)
        memoryicon = QLabel()
        memoryicon.setPixmap(QPixmap('img/memory.png'))
        memorylabel = QLabel("<b>Memory Usage</b>")
        self.memoryvalue = QLabel("Unknown")
        memorylayout.addWidget(memoryicon)
        memorylayout.addWidget(memorylabel)
        memorylayout.addWidget(self.memoryvalue)

        localiplayout = QHBoxLayout()
        localiplayout.setAlignment(Qt.AlignLeft)
        localipicon = QLabel()
        localipicon.setPixmap(QPixmap('img/network.png'))
        localiplabel = QLabel("<b>Local IP Address</b>")
        self.localipvalue = QLabel("0.0.0.0")
        localiplayout.addWidget(localipicon)
        localiplayout.addWidget(localiplabel)
        localiplayout.addWidget(self.localipvalue)

        activewindowlayout = QHBoxLayout()
        activewindowlayout.setAlignment(Qt.AlignLeft)
        activewindowpicon = QLabel()
        activewindowpicon.setPixmap(QPixmap('img/application.png'))
        activewindowlabel = QLabel("<b>Current Activity</b>")
        self.activewindowvalue = QLabel("Unknown")
        activewindowlayout.addWidget(activewindowpicon)
        activewindowlayout.addWidget(activewindowlabel)
        activewindowlayout.addWidget(self.activewindowvalue)


        infobox.addLayout(machinenamelayout)
        infobox.addLayout(oslayout)
        infobox.addLayout(activeuserlayout)
        infobox.addLayout(uptimelayout)
        infobox.addLayout(cpulayout)
        infobox.addLayout(memorylayout)
        infobox.addLayout(localiplayout)
        infobox.addLayout(activewindowlayout)

        # self.obj.outputConsole.setStyleSheet('background-color: #2C2C2C; color:#00FF00')

        hbox.addWidget(infoboxwidget)
        hbox.addLayout(thumbnailtemp)
        self.vbox.setAlignment(Qt.AlignTop)
        self.vbox.addLayout(hbox)